version: '2'
 
services:
  test-runner:
    build: 
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - mysql
      - mssql
      - pgsql
  mysql:
    image: mysql
    container_name: dotnet-test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Rea11ytrong_3"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "Rea11ytrong_3"
      MYSQL_DATABASE: "dotnettest"

  mssql:
    image: microsoft/mssql-server-linux
    container_name: dotnet-test-mssql
    environment:
      ACCEPT_EULA: "Y"   
      SA_PASSWORD: "Rea11ytrong_3"
  pgsql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Rea11ytrong_3"
      POSTGRES_USER: "tester"
      POSTGRES_DB: "dotnettest"
